name: Sweet and Salty
favicon: null
layout_spectrum: 0.1457153877709061
typography_spectrum: 0.6588891928549856
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6545837863814086
  lightness: 0.16933514084666967
  saturation: 0.2908130034338683
  rhythmicContrast: 0.8722030757926404
purpose: []
