name: Sweet and Salty
favicon: null
layout_spectrum: 0.97945
typography_spectrum: 0.72602
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#0e0906'
    - '#a18876'
    - '#3f3432'
    - '#745f4e'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.2908130034338683
  rhythmicContrast: 0.75
purpose: []
